"""baseline schema

Revision ID: 068f7e8aac7a
Revises: 
Create Date: 2026-07-17 11:00:49.479169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '068f7e8aac7a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('url', sa.String(length=512), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('trust_tier', sa.SmallInteger(), nullable=False),
    sa.Column('last_fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('lang', sa.String(length=8), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('digest_mode', sa.String(length=16), nullable=False),
    sa.Column('digest_hour', sa.SmallInteger(), nullable=False),
    sa.Column('min_importance', sa.SmallInteger(), nullable=False),
    sa.Column('last_digest_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_telegram_id'), ['telegram_id'], unique=True)

    op.create_table('deliveries',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('cluster_id', sa.Integer(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'cluster_id')
    )
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('canonical_url', sa.String(length=1024), nullable=False),
    sa.Column('url_hash', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('author', sa.String(length=256), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cluster_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url_hash')
    )
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_items_cluster_id'), ['cluster_id'], unique=False)
        batch_op.create_index('ix_items_published_at', ['published_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_items_source_id'), ['source_id'], unique=False)

    op.create_table('user_topics',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tag', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'tag')
    )
    op.create_table('item_enrichment',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('entities', sa.JSON(), nullable=False),
    sa.Column('importance', sa.SmallInteger(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('model_used', sa.String(length=64), nullable=False),
    sa.Column('enriched_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.PrimaryKeyConstraint('item_id')
    )
    with op.batch_alter_table('item_enrichment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_item_enrichment_importance'), ['importance'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item_enrichment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_item_enrichment_importance'))

    op.drop_table('item_enrichment')
    op.drop_table('user_topics')
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_items_source_id'))
        batch_op.drop_index('ix_items_published_at')
        batch_op.drop_index(batch_op.f('ix_items_cluster_id'))

    op.drop_table('items')
    op.drop_table('deliveries')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_telegram_id'))

    op.drop_table('users')
    op.drop_table('sources')
    # ### end Alembic commands ###
