"""add summary_uz

Revision ID: 57572b3f1f08
Revises: da384ca30b36
Create Date: 2026-07-17 19:25:37.845484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57572b3f1f08'
down_revision: Union[str, Sequence[str], None] = 'da384ca30b36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item_enrichment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('summary_uz', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item_enrichment', schema=None) as batch_op:
        batch_op.drop_column('summary_uz')

    # ### end Alembic commands ###
