"""add text_complete and text_extracted_at

Revision ID: 9d4e34ad6463
Revises: 068f7e8aac7a
Create Date: 2026-07-17 12:26:10.578479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d4e34ad6463'
down_revision: Union[str, Sequence[str], None] = '068f7e8aac7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('text_complete', sa.Boolean(), server_default=sa.text('0'), nullable=False))
        batch_op.add_column(sa.Column('text_extracted_at', sa.DateTime(timezone=True), nullable=True))

    # Rows stored before this column existed all take the default, false. For
    # changelog items that is wrong and destructive: their URL is the whole
    # release notes page, their text is one day's section, and their section is
    # short enough to look thin — so extraction would fetch the page and replace
    # a single day's entry with every entry on it.
    #
    # Ingest only writes text_complete on insert, so nothing else would ever
    # correct these. No-op on a fresh database, which has no such rows.
    op.execute(
        """
        UPDATE items SET text_complete = 1
        WHERE source_id IN (SELECT id FROM sources WHERE kind = 'changelog')
        """
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_column('text_extracted_at')
        batch_op.drop_column('text_complete')

    # ### end Alembic commands ###
