"""add cluster_research

Revision ID: bdebf35264f2
Revises: 57572b3f1f08
Create Date: 2026-07-17 19:51:03.276214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bdebf35264f2'
down_revision: Union[str, Sequence[str], None] = '57572b3f1f08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cluster_research',
    sa.Column('cluster_id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('body_uz', sa.Text(), nullable=True),
    sa.Column('model_used', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('cluster_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cluster_research')
    # ### end Alembic commands ###
